### ISSUE TITLE
Unifi CheckoutOrder and OrderManagementOrder with common interface

### ISSUE THREAD

**Issue by fredrik-rambris** [klarna/kco_rest_java#22]
When dealing with orders CheckoutOrder and OrderManagementOrder have many common attributes. They should inherit from the same superclass or implement the same interface so they can be used by the same code if that code is not dependant of the specific implementation.

**Comment by alexions** [comment]
Hi @fredrik-rambris 

Thank you for the proposal. It's a very good idea and I really like this! But there are number of issues.

By internal Klarna architecture Checkout and Order Management (and Klarna Payment) are totally different services and each service has its own Order model. These models are veeeery very similar to each other, but still, they are different, with different fields and properties and at this point of time cannot be joined/unified.

It means, that this is impossible for now to create a single interface, since these Models have a different properties.

So for now it's a forced solution to have a separate non-unified models, but I hope it will be solved in the future and we're actually, working on the solution.
